### ISSUE TITLE
Make update checker more flexible

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/FastAsyncVoxelSniper#150]
Currently we run the update checker task every 6 hours. We don't push updates much frequent to utilize these 6 hours.
I guess, we can either make it configurable or run every 12/24 hours?
I'm open for suggestions.

**Comment by mibby** [comment]
I'd still like to see an option to disable the update check entirely personally. https://github.com/IntellectualSites/fastasyncvoxelsniper/issues/97 https://github.com/IntellectualSites/fastasyncvoxelsniper/commit/871f26bd08651286e0fc0a11f4cc56c92f171c4b was nice to avoid in-game spam, but since I intentionally use specific builds and always use the latest git action build for testing, I don't necessarily need to see console complaining about using snapshot releases periodically.
