### ISSUE TITLE
TODOs for future releases

### ISSUE THREAD

**Issue by Aurelien30000** [IntellectualSites/fastasyncvoxelsniper#51]
Thank you again and again for precise review, pr is almost ready imo, **needs some further testing though, brush by brush** (I'll do it on my side on Saturday).

_No more changes due to lack of time to devote to FAVS, huge inconsistencies with for instance spiral stair case brush will be addressed later, I will try for the end of August._

_Originally posted by @Aurelien30000 in https://github.com/IntellectualSites/FastAsyncVoxelSniper/issues/50#issuecomment-897994254_

**Comment by NotMyFault** [comment]
A few other things that may be handy:
- Sing overwrite brush not overwriting existing lines, e.g you specify line 1 to be edited and the outcome should only be the updated version with line 1 editor, rather than yeeting the entire signs content and put only the new line 1 up.
- Tab completion for basic commands such as `/vs toggle, info` etc.

**Comment by Aurelien30000** [comment]
> Sing overwrite brush not overwriting existing lines, e.g you specify line 1 to be edited and the outcome should only be the updated version with line 1 editor, rather than yeeting the entire signs content and put only the new line 1 up.

Line toggle 🤔
